const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const User = require('../models/User');
const Place = require('../models/Place');
const nodemailer = require('nodemailer');
const { Resend } = require('resend');
const OpenAI = require('openai');

// @route   POST /api/user/favorites/:id
// @desc    Toggle favorite status for a place
router.post('/favorites/:id', auth, async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    const placeId = req.params.id;

    if (user.favorites.includes(placeId)) {
      user.favorites = user.favorites.filter(id => id !== placeId);
    } else {
      user.favorites.push(placeId);
    }

    await user.save();
    res.json(user.favorites);
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   POST /api/user/plan-trip
// @desc    Send trip itinerary via email
router.post('/plan-trip', auth, async (req, res) => {
  const { itinerary } = req.body;
  try {
    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(404).json({ msg: 'User not found' });
    }

    let emailHtml = "";
    
    if (itinerary && Array.isArray(itinerary)) {
      // Use the provided day-by-day itinerary
      emailHtml = itinerary.map(day => `
        <div style="margin-bottom: 30px; border: 1px solid #eee; border-radius: 8px; overflow: hidden; background: #fff;">
          <div style="background: #e67e22; color: white; padding: 10px 20px; font-weight: bold;">
            Day ${day.day} - ${day.taluka} Exploration
          </div>
          <div style="padding: 15px;">
            ${day.places.map((p, idx) => `
              <div style="padding: 10px 0; border-bottom: ${idx === day.places.length - 1 ? 'none' : '1px solid #f0f0f0'};">
                <span style="color: #666; font-size: 11px; text-transform: uppercase;">${idx === 0 ? 'Morning' : idx === 1 ? 'Afternoon' : 'Evening'}</span>
                <h4 style="margin: 5px 0; color: #333;">${p.name}</h4>
                <p style="margin: 0; color: #888; font-size: 12px;">${p.category} | ${p.talukaName}</p>
              </div>
            `).join('')}
            
            <div style="margin-top: 15px; padding-top: 15px; border-top: 2px dashed #eee; background: #fffaf0; padding: 10px;">
              <h5 style="margin: 0 0 10px 0; color: #e67e22;">🍽️ Recommended Dining & Stay</h5>
              ${day.restaurant ? `<p style="margin: 5px 0; font-size: 13px;"><strong>Food:</strong> ${day.restaurant.name}</p>` : ''}
              ${day.hotel ? `<p style="margin: 5px 0; font-size: 13px;"><strong>Stay:</strong> ${day.hotel.name}</p>` : ''}
            </div>
          </div>
        </div>
      `).join('');
    } else {
      // Fallback to Wishlist-based itinerary
      if (!user.favorites || user.favorites.length === 0) {
        return res.status(400).json({ msg: 'Your wishlist is empty!' });
      }
      const places = await Place.find({ id: { $in: user.favorites } });
      emailHtml = places.map(p => `
        <div style="border-bottom: 1px solid #eee; padding: 15px 0;">
          <h3 style="color: #e67e22; margin: 0;">${p.name}</h3>
          <p style="margin: 5px 0; color: #666;"><strong>Category:</strong> ${p.category}</p>
          <p style="margin: 10px 0; font-style: italic;">${p.description}</p>
        </div>
      `).join('');
    }

    const fullHtml = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 12px; overflow: hidden; background-color: #fcfcfc;">
        <div style="background: linear-gradient(135deg, #f39c12, #e67e22); color: white; padding: 40px 20px; text-align: center;">
          <h1 style="margin: 0; font-size: 28px;">Your Kolhapur Journey</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Personalized Itinerary for ${user.name}</p>
        </div>
        <div style="padding: 30px;">
          <p style="color: #333; line-height: 1.6;">Hi ${user.name}, your adventure is ready! We've crafted this plan to help you experience the best of Kolhapur.</p>
          <div style="margin-top: 30px;">
            ${emailHtml}
          </div>
          <div style="margin-top: 40px; text-align: center; border-top: 1px solid #eee; padding-top: 20px;">
            <p style="color: #e67e22; font-weight: bold; margin-bottom: 5px;">Happy Traveling! ❤️</p>
            <p style="color: #999; font-size: 11px;">This itinerary was generated by the Kolhapur Tourism App.</p>
          </div>
        </div>
      </div>
    `;

    // --- EMAIL SENDING LOGIC ---
    let transporter;
    let fromEmail = '"Kolhapur Tourism" <noreply@kolhapur-tourism.com>';

    if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
      transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT) || 587,
        secure: process.env.SMTP_SECURE === 'true',
        auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
      });
      fromEmail = `"Kolhapur Tourism" <${process.env.SMTP_USER}>`;
    } else if (process.env.RESEND_API_KEY) {
      const resend = new Resend(process.env.RESEND_API_KEY);
      const { data, error } = await resend.emails.send({
        from: 'Kolhapur Tourism <onboarding@resend.dev>',
        to: user.email,
        subject: `Your Planned Trip to Kolhapur - ${user.name}`,
        html: fullHtml
      });
      if (error) throw error;
      return res.json({ msg: 'Itinerary sent via Resend!' });
    } else {
      // Test Fallback
      let testAccount = await nodemailer.createTestAccount();
      transporter = nodemailer.createTransport({
        host: "smtp.ethereal.email",
        port: 587,
        secure: false,
        auth: { user: testAccount.user, pass: testAccount.pass }
      });
    }

    if (transporter) {
      await transporter.sendMail({
        from: fromEmail,
        to: user.email,
        subject: `Your Planned Trip to Kolhapur - ${user.name}`,
        html: fullHtml
      });
      res.json({ msg: 'Trip itinerary sent to your email!' });
    }

  } catch (err) {
    console.error('Plan trip error:', err);
    res.status(500).json({ error: 'Failed to send email. Check server configuration.' });
  }
});

// @route   POST /api/user/ai/chat
// @desc    Get AI travel advice for Kolhapur
router.post('/ai/chat', async (req, res) => {
  const { message, history } = req.body;
  if (!message) return res.status(400).json({ error: 'Message is required' });

  try {
    // 1. Fetch context (Places, Talukas) to make the AI an expert
    const places = await Place.find().select('name category description talukaName visitDuration bestTimeToVisit');
    const knowledgeBase = places.map(p => 
      `${p.name} (${p.category}) in ${p.talukaName}. Best time: ${p.bestTimeToVisit}. Duration: ${p.visitDuration}. Info: ${p.description.slice(0, 100)}...`
    ).join('\n');

    // 2. Initialize DeepSeek (using OpenAI compatibility)
    const openai = new OpenAI({
      apiKey: process.env.DEEPSEEK_API_KEY,
      baseURL: 'https://integrate.api.nvidia.com/v1'
    });

    // 3. Prepare Prompt
    const systemPrompt = `You are the "Kolhapur Tourism Assistant", a friendly expert on Kolhapur, Maharashtra, India.
Your goal is to help tourists plan their trip, suggest places, and provide local tips.
Use the following knowledge base of real places in Kolhapur to provide accurate answers:
${knowledgeBase}

If a place is not in the list, you can still talk about it if you know it's in Kolhapur, but prioritize the ones above.
Keep responses concise, helpful, and welcoming. Use emojis related to travel.
If asked for an itinerary, try to group places by Taluka (Region) to save travel time.`;

    const messages = [
      { role: 'system', content: systemPrompt },
      ...(history || []).slice(-5), // Include last 5 messages for context
      { role: 'user', content: message }
    ];

    // 4. Call NVIDIA NIM (Llama 3.1)
    const completion = await openai.chat.completions.create({
      model: 'meta/llama-3.1-8b-instruct',
      messages: messages,
      temperature: 0.7,
      max_tokens: 500,
    });

    const aiResponse = completion.choices[0].message.content;
    res.json({ response: aiResponse });

  } catch (err) {
    console.error('AI Chat Error:', err);
    res.status(500).json({ error: 'AI Assistant is temporarily unavailable. Please try again later.' });
  }
});

module.exports = router;
