const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const User = require('../models/User');
const Place = require('../models/Place');
const nodemailer = require('nodemailer');
const { Resend } = require('resend');
const OpenAI = require('openai');

// @route   POST /api/user/favorites/:id
// @desc    Toggle favorite status for a place
router.post('/favorites/:id', auth, async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    const placeId = req.params.id;

    if (user.favorites.includes(placeId)) {
      user.favorites = user.favorites.filter(id => id !== placeId);
    } else {
      user.favorites.push(placeId);
    }

    await user.save();
    res.json(user.favorites);
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server Error');
  }
});

// @route   POST /api/user/plan-trip
// @desc    Send trip itinerary via email
router.post('/plan-trip', auth, async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(404).json({ msg: 'User not found' });
    }

    if (!user.favorites || user.favorites.length === 0) {
      return res.status(400).json({ msg: 'Your wishlist is empty!' });
    }

    // Fetch full details for all favorited places
    if (!user.favorites) {
      user.favorites = [];
    }
    const places = await Place.find({ id: { $in: user.favorites } });
    console.log(`Planning trip for ${user.email} with ${places.length} places`);

    const placeListHtml = places.map(p => `
      <div style="border-bottom: 1px solid #eee; padding: 15px 0;">
        <h3 style="color: #e67e22; margin: 0;">${p.name}</h3>
        <p style="margin: 5px 0; color: #666;"><strong>Category:</strong> ${p.category}</p>
        <p style="margin: 5px 0; color: #666;"><strong>Duration:</strong> ${p.visitDuration}</p>
        <p style="margin: 5px 0; color: #666;"><strong>Best Time:</strong> ${p.bestTimeToVisit}</p>
        <p style="margin: 10px 0; font-style: italic;">${p.description}</p>
      </div>
    `).join('');

    // --- EMAIL TRANSPORTER (SMTP / GMAIL) ---
    // We prioritize SMTP if provided, as it allows unrestricted sending to any recipient.
    console.log('Checking SMTP config:', { 
      host: process.env.SMTP_HOST ? 'YES' : 'NO', 
      user: process.env.SMTP_USER ? 'YES' : 'NO', 
      pass: process.env.SMTP_PASS ? 'YES' : 'NO' 
    });
    
    if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
      console.log(`Using SMTP: ${process.env.SMTP_HOST}`);
      const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT) || 587,
        secure: process.env.SMTP_SECURE === 'true',
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS
        }
      });

      await transporter.sendMail({
        from: `"Kolhapur Tourism" <${process.env.SMTP_USER}>`,
        to: user.email,
        subject: `Your Planned Trip to Kolhapur - ${user.name}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;">
            <div style="background: linear-gradient(to right, #f39c12, #e67e22); color: white; padding: 20px; text-align: center;">
              <h1 style="margin: 0;">Your Kolhapur Itinerary</h1>
            </div>
            <div style="padding: 20px;">
              <p>Hi ${user.name},</p>
              <p>Here is your personalized travel plan for Kolhapur based on your wishlist. We hope you have an amazing journey! ❤️</p>
              ${placeListHtml}
              <div style="margin-top: 30px; text-align: center; color: #888; font-size: 12px;">
                <p>Generated by Kolhapur Tourism App</p>
              </div>
            </div>
          </div>
        `
      });
      return res.json({ msg: 'Trip itinerary sent via Gmail SMTP!' });
    }

    // --- EMAIL TRANSPORTER (RESEND) ---
    if (process.env.RESEND_API_KEY) {
      console.log('Using Resend SDK for email');
      const resend = new Resend(process.env.RESEND_API_KEY);
      
      const { data, error } = await resend.emails.send({
        from: 'Kolhapur Tourism <noreply@kolhapur-tourism.com>',
        to: user.email,
        subject: `Your Planned Trip to Kolhapur - ${user.name}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;">
            <div style="background: linear-gradient(to right, #f39c12, #e67e22); color: white; padding: 20px; text-align: center;">
              <h1 style="margin: 0;">Your Kolhapur Itinerary</h1>
            </div>
            <div style="padding: 20px;">
              <p>Hi ${user.name},</p>
              <p>Here is your personalized travel plan for Kolhapur based on your wishlist. We hope you have an amazing journey! ❤️</p>
              ${placeListHtml}
              <div style="margin-top: 30px; text-align: center; color: #888; font-size: 12px;">
                <p>Generated by Kolhapur Tourism App</p>
              </div>
            </div>
          </div>
        `
      });

      if (error) {
        console.error('RESEND API ERROR:', error);
        if (error.name === 'validation_error' || error.message.includes('verify')) {
          return res.status(403).json({ 
            error: 'Resend Free Tier: You can only send emails to your own account email (ayajmulla2341@gmail.com). To send to others, please verify your domain (kolhapur-tourism.com) in Resend!',
            details: error 
          });
        }
        return res.status(500).json({ error: error.message, details: error });
      }

      console.log('Email sent successfully via Resend:', data.id);
      return res.json({ msg: 'Trip itinerary sent to your email via Resend!' });
    }

    // --- FALLBACK: NODEMAILER (ETHEREAL) ---
    console.log('No real SMTP/Resend provided, falling back to Ethereal...');
    let testAccount = await nodemailer.createTestAccount();
    const transporter = nodemailer.createTransport({
      host: "smtp.ethereal.email",
      port: 587,
      secure: false,
      auth: {
        user: testAccount.user,
        pass: testAccount.pass
      }
    });

    const mailOptions = {
      from: '"Kolhapur Tourism" <noreply@kolhapur-tourism.com>',
      to: user.email,
      subject: `Your Planned Trip to Kolhapur - ${user.name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;">
          <div style="background: linear-gradient(to right, #f39c12, #e67e22); color: white; padding: 20px; text-align: center;">
            <h1 style="margin: 0;">Your Kolhapur Itinerary</h1>
          </div>
          <div style="padding: 20px;">
            <p>Hi ${user.name},</p>
            <p>Here is your personalized travel plan for Kolhapur based on your wishlist. We hope you have an amazing journey! ❤️</p>
            ${placeListHtml}
            <div style="margin-top: 30px; text-align: center; color: #888; font-size: 12px;">
              <p>Generated by Kolhapur Tourism App</p>
            </div>
          </div>
        </div>
      `
    };

    await transporter.sendMail(mailOptions);
    res.json({ msg: 'Trip itinerary sent to your email (Ethereal Preview)!' });

  } catch (err) {
    console.error('Plan trip error:', err);
    res.status(500).json({ error: 'Failed to send email. Check server configuration.' });
  }
});

// @route   POST /api/user/ai/chat
// @desc    Get AI travel advice for Kolhapur
router.post('/ai/chat', async (req, res) => {
  const { message, history } = req.body;
  if (!message) return res.status(400).json({ error: 'Message is required' });

  try {
    // 1. Fetch context (Places, Talukas) to make the AI an expert
    const places = await Place.find().select('name category description talukaName visitDuration bestTimeToVisit');
    const knowledgeBase = places.map(p => 
      `${p.name} (${p.category}) in ${p.talukaName}. Best time: ${p.bestTimeToVisit}. Duration: ${p.visitDuration}. Info: ${p.description.slice(0, 100)}...`
    ).join('\n');

    // 2. Initialize DeepSeek (using OpenAI compatibility)
    const openai = new OpenAI({
      apiKey: process.env.DEEPSEEK_API_KEY,
      baseURL: 'https://integrate.api.nvidia.com/v1'
    });

    // 3. Prepare Prompt
    const systemPrompt = `You are the "Kolhapur Tourism Assistant", a friendly expert on Kolhapur, Maharashtra, India.
Your goal is to help tourists plan their trip, suggest places, and provide local tips.
Use the following knowledge base of real places in Kolhapur to provide accurate answers:
${knowledgeBase}

If a place is not in the list, you can still talk about it if you know it's in Kolhapur, but prioritize the ones above.
Keep responses concise, helpful, and welcoming. Use emojis related to travel.
If asked for an itinerary, try to group places by Taluka (Region) to save travel time.`;

    const messages = [
      { role: 'system', content: systemPrompt },
      ...(history || []).slice(-5), // Include last 5 messages for context
      { role: 'user', content: message }
    ];

    // 4. Call DeepSeek (NVIDIA NIM)
    const completion = await openai.chat.completions.create({
      model: 'deepseek-ai/deepseek-v3.1',
      messages: messages,
      temperature: 0.7,
      max_tokens: 500,
    });

    const aiResponse = completion.choices[0].message.content;
    res.json({ response: aiResponse });

  } catch (err) {
    console.error('AI Chat Error:', err);
    res.status(500).json({ error: 'AI Assistant is temporarily unavailable. Please try again later.' });
  }
});

module.exports = router;
